#!/bin/bash

# ==============================================================================
# OpenAuto ALSA Configurator v5 (The Fix)
# ==============================================================================

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Error: Please run as root (sudo ./setup-audio.sh)${NC}"
  exit 1
fi

clear
echo -e "${CYAN}==========================================${NC}"
echo -e "${CYAN}   OpenAuto ALSA Configurator v5          ${NC}"
echo -e "${CYAN}==========================================${NC}"

# 1. Playback Device
echo -e "\n${YELLOW}[1] Playback Devices:${NC}"
aplay -l | grep "^card"
echo -e "\n${GREEN}Enter Playback Card Number (e.g. 0):${NC}"
read -p "Card: " PLAY_CARD

# 2. Capture Device
echo -e "\n${YELLOW}[2] Capture Devices:${NC}"
arecord -l | grep "^card"
echo -e "${CYAN}---------------------------------------------${NC}"
echo -e " [0-9] : Real Microphone Card Number"
echo -e " [N]   : Null Device (Virtual Mic)"
echo -e "${CYAN}---------------------------------------------${NC}"
read -p "Selection: " CAP_SELECTION

if [[ "$CAP_SELECTION" == "N" || "$CAP_SELECTION" == "n" ]]; then
    USE_NULL_MIC=true
else
    USE_NULL_MIC=false
    CAP_CARD=$CAP_SELECTION
fi

# 3. Quality
echo -e "\n${YELLOW}[3] Playback Quality:${NC}"
echo "   1) 48000 Hz"
echo "   2) 96000 Hz"
echo "   3) 192000 Hz (Fixed in this version)"
read -p "Select [1-3]: " RATE_CHOICE
case $RATE_CHOICE in
    1) SAMPLE_RATE=48000 ;;
    2) SAMPLE_RATE=96000 ;;
    3) SAMPLE_RATE=192000 ;;
    *) SAMPLE_RATE=48000 ;;
esac

# 4. Buffers
echo -e "\n${YELLOW}[4] Buffer Mode:${NC}"
echo "   1) Standard"
echo "   2) Android Mode (Anti-Stutter for RK3229)"
read -p "Select [1-2]: " BUFFER_CHOICE
if [ "$BUFFER_CHOICE" == "2" ]; then
    PERIOD_SIZE=8192
    BUFFER_SIZE=65536
    echo -e "${GREEN}>> Deep Buffers Enabled${NC}"
else
    PERIOD_SIZE=1024
    BUFFER_SIZE=4096
    echo -e "${GREEN}>> Standard Buffers Enabled${NC}"
fi

# 5. Generate Config
echo -e "\n${YELLOW}[5] Generating /etc/asound.conf...${NC}"

cat <<EOF > /etc/asound.conf
# Generated by OpenAuto Audio Configurator v5
# Rate: $SAMPLE_RATE | Buffer: $BUFFER_SIZE

# -----------------------------
# 1. Hardware Mixer (The Target)
# -----------------------------
pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_perm 0666
    slave {
        pcm "hw:${PLAY_CARD},0"
        rate ${SAMPLE_RATE}
        format S32_LE
        channels 2
        period_size ${PERIOD_SIZE}
        buffer_size ${BUFFER_SIZE}
    }
    bindings {
        0 0
        1 1
    }
}

# -----------------------------
# 2. Software Volume
# -----------------------------
pcm.my_softvol {
    type softvol
    slave.pcm "plug:dmixer"
    control {
        name "Master"
        card ${PLAY_CARD}
    }
    min_dB -51.0
    max_dB 0.0
}

# -----------------------------
# 3. Playback Resampler (THE FIX)
# -----------------------------
# This forces the rate conversion BEFORE it enters the mixer.
# It solves the "Assertion Failed" error with 192k/Huge Buffers.
pcm.playback_upped {
    type plug
    slave {
        pcm "my_softvol"
        rate ${SAMPLE_RATE}
    }
}
EOF

# Append Microphone Section
if [ "$USE_NULL_MIC" == "true" ]; then
cat <<EOF >> /etc/asound.conf

# 4. Null Mic
pcm.mic_snooper {
    type plug
    slave.pcm "null"
}
EOF
else
cat <<EOF >> /etc/asound.conf

# 4. Hardware Mic
pcm.mic_snooper {
    type dsnoop
    ipc_key 2048
    ipc_perm 0666
    slave {
        pcm "hw:${CAP_CARD},0"
        rate 48000
        channels 2
        format S16_LE
    }
}
EOF
fi

cat <<EOF >> /etc/asound.conf

# -----------------------------
# 5. Asym Container (OpenAuto Device)
# -----------------------------
pcm.openauto_device {
    type asym
    # Playback goes through the RESAMPLER first
    playback.pcm "playback_upped"
    capture.pcm "plug:mic_snooper"
}

# -----------------------------
# 6. Default Endpoint
# -----------------------------
pcm.!default {
    type plug
    slave.pcm "openauto_device"
}

ctl.!default {
    type hw
    card ${PLAY_CARD}
}
EOF

echo -e "${GREEN}>> Config written.${NC}"

# 6. Restart
echo -e "\n${YELLOW}[6] Applying Changes...${NC}"
/etc/init.d/alsa-utils stop > /dev/null 2>&1
rm -f /var/lib/alsa/asound.state
rm -f /etc/asound.state
/etc/init.d/alsa-utils start > /dev/null 2>&1

# 7. Verification
echo -e "\n${YELLOW}[7] Testing...${NC}"
TEST_OUTPUT=$(speaker-test -D default -c 2 -l 1 2>&1)

if [ $? -eq 0 ]; then
    echo -e "${GREEN}SUCCESS! Audio is working.${NC}"
else
    echo -e "${RED}ERROR: Audio initialization failed!${NC}"
    echo "$TEST_OUTPUT"
fi