#!/bin/bash
#  * Project: OpenAuto
#  * This file is part of openauto project.
#  * Copyright (C) 2025 OpenCarDev Team
#  *
#  *  openauto is free software: you can redistribute it and/or modify
#  *  it under the terms of the GNU General Public License as published by
#  *  the Free Software Foundation; either version 3 of the License, or
#  *  (at your option) any later version.
#  *
#  *  openauto is distributed in the hope that it will be useful,
#  *  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  *  GNU General Public License for more details.
#  *
#  *  You should have received a copy of the GNU General Public License
#  *  along with openauto. If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
    purge|remove)
        # Disable services
        if [ -x /bin/systemctl ]; then
            /bin/systemctl stop openauto.service 2>/dev/null || true
            /bin/systemctl stop openauto-btservice.service 2>/dev/null || true
            /bin/systemctl disable openauto.service 2>/dev/null || true
            /bin/systemctl disable openauto-btservice.service 2>/dev/null || true
        fi

        # Unmask getty@tty2 to restore normal tty behavior
        if [ -x /bin/systemctl ]; then
            echo "Restoring getty@tty2 service..."
            /bin/systemctl unmask getty@tty2.service 2>/dev/null || true
        fi

        # Remove ldconfig entry
        if [ -f /etc/ld.so.conf.d/openauto.conf ]; then
            rm -f /etc/ld.so.conf.d/openauto.conf
            ldconfig || true
        fi

        # Reload systemd
        if [ -x /bin/systemctl ]; then
            /bin/systemctl daemon-reload || true
        fi

        echo "OpenAuto removed. getty@tty2 has been restored."
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
